# Generated by Django 3.1.4 on 2021-09-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_recruiter_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='name',
        ),
    ]
